【WIP】ログイン画面、新規登録画面、送付先登録画面の実装
shunAutumn/fleamarket_sample_78b pull request #32
Opened 2020-10-14 15:35 UTC by donmkbtgmxxx

#What

#######ユーザー新規登録画面

ユーザー名、パスワードといった必要な項目を入力するための欄を作成。
必須事項に対して『必須』の表示。

#######送付先住所登録画面
市町村、連絡先といった必要な項目を入力するための蘭を作成。
必須事項に対して『必須』の表示。

#######ログイン画面
メールアドレスとパスワード入力によりログインするための欄を作成。
新規登録へのリンク作成。

######共通
トップページ等から、作成した各画面に遷移できる。

#Why
利用するために必須の機能であるため。

2020-10-14 16:56 UTC, shunAutumn commented
LGTMです。
もしよかったら次からクラス名などは英語で書かれた方が実際の現場に出た時に苦労しないと思います。
生意気言ってすみません。

2020-10-15 11:34 UTC, akitazu14 requested changes
以下の修正をお願いしたいです。

2020-10-15 11:34 UTC, akitazu14 commented on app/views/devise/sessions/new.html.haml
> += form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f|
再ログイン先のurlが新規登録のパスになっています。session_pathへ戻しておいてください。

2020-10-15 11:34 UTC, akitazu14 commented on app/views/devise/registrations/new.html.haml
> +            = f.date_select :birthday, class:'text__region'
クラス名はこのままで構わないので、元あったオプションを付けておいて欲しいです。
= f.date_select :birthday, use_month_numbers: true, start_year: 1900, default: Date.new(1989, 1, 1)

2020-10-18 04:16 UTC, akitazu14 commented
LGTMです。

2020-10-18 04:40 UTC, donmkbtgmxxx commented on app/views/devise/sessions/new.html.haml
> += form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f|
修正しました。

2020-10-18 04:40 UTC, donmkbtgmxxx commented on app/views/devise/registrations/new.html.haml
> +            = f.date_select :birthday, class:'text__region'
修正しました。

2020-10-18 04:43 UTC, donmkbtgmxxx commented
> LGTMです。
> もしよかったら次からクラス名などは英語で書かれた方が実際の現場に出た時に苦労しないと思います。
> 生意気言ってすみません。

いえ。ありがとうございます。
このようなアドバイスはとてもありがたいので、していただけると幸いです。

2020-10-18 05:15 UTC, miyagit commented
コンフリクトが起きているので、コンフリクトを解消しましょう。
コンフリクトの解消方法が分からなければ、下記のサイトに解消方法が載っているので、参考にして頂ければと思います。

https://qiita.com/crarrry/items/c5964512e21e383b73da

コンフリクトはこれから仕事をする現場でも必ず起きるモノなので、ここで
コンフリクトの解消方法を理解すると必ず仕事に役立つので、頑張りましょう！

2020-10-18 06:01 UTC, donmkbtgmxxx commented
> コンフリクトが起きているので、コンフリクトを解消しましょう。
> コンフリクトの解消方法が分からなければ、下記のサイトに解消方法が載っているので、参考にして頂ければと思います。
> 
> https://qiita.com/crarrry/items/c5964512e21e383b73da
> 
> コンフリクトはこれから仕事をする現場でも必ず起きるモノなので、ここで
> コンフリクトの解消方法を理解すると必ず仕事に役立つので、頑張りましょう！

解消いたしました！

2020-10-19 06:23 UTC, TOMARUMARU commented
LGTMです。お疲れ様でした。mergeして次に進みましょう。

2020-10-20 07:24 UTC, merged